---
title: "ivygapSE basics"
author: "Vincent J. Carey, stvjc at channing.harvard.edu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{ivygapSE basics}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---


The ivygapSE package includes molecular, imaging, and 
limited clinical data on glioblastoma (GBM) patients.

Expression data (RNA-seq) was developed in a complex design
involving tissue blocks and subblocks and a selection process.
See documents at https://vjcitn.github.io/ivygapSE for more
details.

To work with the available survival data in an elementary
way, the following steps can be taken.


```{r genes}
library(ivygapSE)
library(MASS)
library(nlme)

data(ivySE)

# In this code we drop out the "CT"-only samples
struc = as.character(colData(ivySE)$structure_acronym)
spls = strsplit(struc, "-")
basis = vapply(spls, function(x) x[1], character(1))
specific = which(basis!= "CT")
iseSP = ivySE[ , specific]

useful = c("EIF4E3","ATP1A2","FGFR3","LMO3","NCAN","FXYD1","PSD2","PRODH",
           "HIF3A","HRSP12","KCNN3","PPM1K","KCNJ10","ADCYAP1R1","BMP7",
           "KAT2B","CNTN1","SAMD9L","SLC7A11","ECHDC2","FAM181B","SALL2","SASH1",
           
           "CCL4","CCL3","EGR3","IL1B","CCL2","GPR56","TNF","CX3CR1","SERPINE1","CSF1",
           "RAMP1","IL6ST","IL1A","PDE3B","CD276","FLT1","CXCL12","NR4A1","CSF1R","CCR1",
           "RHOB","SPHK1","SORL1","IL6R","VASH1","ADAM28","STAMBPL1","ADAMTSL2")

splim = iseSP[useful,]


cd = colData(splim)
stac = cd$structure_acronym
stac1 = sapply(strsplit(stac, "-"), "[[", 1)
table(stac1)

eexp = as.numeric(log(assay(splim["EIF4E3",])+1))
newdf = data.frame(eexp=eexp, id=splim$tumor_id, bl=splim$block_name)

# it would be nice to generalize so that LE and IT and other types of
# tissue classification could be modeled easily


newdf$isLE = ifelse(stac1=="LE", 1, 0)
table(newdf$isLE)

fit_mixed_logistic = function( SE = splim, gene, dataframe, verbose=FALSE ) {
  stopifnot(all(c("id", "bl", "isLE") %in% names(dataframe)))
  stopifnot(gene %in% rownames(SE))
  dataframe[[gene]] = as.numeric(log(assay(SE[gene,])+1))
  fmla = as.formula(paste("isLE", "~", gene))
  glmmPQL(fmla, data=dataframe, fam=binomial, random=~1|id/bl, verbose=verbose)
  }

ff = lapply(useful, function(x) fit_mixed_logistic( SE=splim, gene=x, dataframe=newdf) )
names(ff) = useful

summary(ff[[1]])

summary(ff[[2]])
